# Generated by Django 5.0.6 on 2024-05-27 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='worker.worker', verbose_name='Workder'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date/Time'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='worker.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Phone Number'),
        ),
    ]
